############################################################
# Kafka properties
############################################################
kafka:
  server: 0.0.0.0:29092
  topic: stock_events
  ksql:
    host: 0.0.0.0
    port: 8088
    table: stock_table

############################################################
# DB properties
############################################################
spring:
  h2:
    console:
      enabled: true
      path: "/h2-console"
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:mydb
      username: sa
      password:
      driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2
      schema-locations: classpath:db/schema-h2.sql

############################################################
# Logging
############################################################
logging:
  level:
    com.piotr.stock.streaming: debug