############################################################
# Kafka properties
############################################################
kafka:
  server: 0.0.0.0:29092
  topic: stock_events
  ksql:
    host: 0.0.0.0
    port: 8088
    table: stock_table

############################################################
# Logging
############################################################
logging:
  level:
    com.piotr.stock.streaming: debug